site_name: Doxide
site_description: Modern documentation for Modern C++. Configure with YAML, output Markdown.
site_url: https://doxide.org
repo_url: https://github.com/lawmurray/doxide
repo_name: lawmurray/doxide
extra:
  social:
    - icon: material/github
      link: https://github.com/lawmurray
    - icon: material/mastodon 
      link: https://fosstodon.org/@lawmurray
    - icon: material/web
      link: https://indii.org
    - icon: material/email
      link: mailto:lawrence@indii.org

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo_white.svg
  favicon: assets/logo_red.svg
  features:
    - navigation.indexes
    - navigation.footer
    - announce.dismiss
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: material/github

markdown_extensions:
  - def_list
  - attr_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true 
plugins:
  - search
  - social
extra_css:
  - stylesheets/doxide.css

nav:
  - index.md
  - installation.md
  - getting-started.md
  - configuring.md
  - command-line.md
  - writing.md
  - organizing.md
  - parsing.md
  - demo/index.md
  - questions-and-answers.md
