version: 2.1

executors:
  linux:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    environment:
      PREFIX: /usr/local
      VERBOSE: 1

  mac:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    environment:
      PREFIX: /usr/local
      CPATH: /usr/local/include
      LIBRARY_PATH: /usr/local/lib
      VERBOSE: 1

  win:
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    resource_class: 'windows.medium'
    environment:
      PREFIX: /usr/local
      CXXFLAGS: /I /usr/local/include
      LDFLAGS: /LIBPATH:/usr/local/lib
      VERBOSE: 1
      CMAKE_GENERATOR: Visual Studio 17 2022
      CMAKE_GENERATOR_PLATFORM: x64
      CMAKE_CONFIG_TYPE: Release  # otherwise cmake install fails

commands:

  environment:
    parameters:
      os:
        type: string
    steps:
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive --depth 1
      - when:
          condition:
            equal: [<< parameters.os >>, linux]
          steps:
            - run:
                name: Install dependencies
                command: |
                  sudo apt update --assume-yes
                  sudo apt install --assume-yes --no-install-recommends \
                    cmake \
                    g++ \
                    lcov \
                    libyaml-dev \
                    libcli11-dev
                  sudo pip3 install mkdocs mkdocs-material
      - when:
          condition:
            equal: [<< parameters.os >>, mac]
          steps:
            - run:
                name: Install dependencies
                command: |
                  HOMEBREW_NO_AUTO_UPDATE=1 brew install \
                    cmake \
                    libyaml \
                    cli11
                  pip3 install mkdocs mkdocs-material
      - when:
          condition:
            equal: [<< parameters.os >>, win]
          steps:
            - run:
                name: Install dependencies
                command: |
                  choco install -y cmake.portable mkdocs mkdocs-material sudo
            - build:
                dir: contrib/libyaml
            - build:
                dir: contrib/CLI11

  build:
    description: Build a package
    parameters:
      dir:
        description: Directory containing the package
        type: string
    steps:
      - run:
          name: Build << parameters.dir >>
          command: |
              cd << parameters.dir >>
              mkdir build
              cd build
              cmake .. -DCMAKE_BUILD_TYPE=Release
              cmake --build . --config Release
              cmake --install . --config Release --prefix $PREFIX

  test:
    steps:
      - run:
          name: Init test
          command: |
            mkdir hello
            cd hello
            doxide init
      - run:
          name: Build test
          command: |
            doxide build
      - run:
          name: MkDocs test
          command: |
            mkdocs build

jobs:

  all:
    parameters: 
      os:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - environment:
          os: << parameters.os >>
      - build:
          dir: .
      - test

  deploy:
    executor: linux
    steps:
      - run:
          name: Trigger package update
          command: |
              curl -X POST https://circleci.com/api/v2/project/gh/lawmurray/download.indii.org/pipeline \
                --header "Circle-Token: $CIRCLE_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch": "main"}'

workflows:

  version: 2
  all:
    jobs:
      - all:
          matrix:
            parameters:
              os:
                - linux
                - mac
                - win

      - deploy:
          requires:
            - all
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
