version: 2.1

orbs:
  win: circleci/windows@5.0

executors:
  linux:
    machine:
      image: ubuntu-2204:current
    resource_class: medium

  mac:
    macos:
      xcode: 14.2.0

commands:

  environment:
    parameters: 
      os:
        type: string
    steps:
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive --depth 1
      - when:
          condition:
            equal: [<< parameters.os >>, linux]
          steps:
            - run:
                name: Install dependencies
                command: |
                  sudo apt update --assume-yes
                  sudo apt install --assume-yes --no-install-recommends \
                    cmake \
                    g++ \
                    lcov \
                    libyaml-dev \
                    libcli11-dev
                  sudo pip3 install mkdocs mkdocs-material
      - when:
          condition:
            equal: [<< parameters.os >>, mac]
          steps:
            - run:
                name: Install dependencies
                command: |
                  HOMEBREW_NO_AUTO_UPDATE=1 brew install \
                    cmake
                  pip3 install mkdocs mkdocs-material
      - when:
          condition:
            equal: [<< parameters.os >>, win/default]
          steps:
            - run:
                name: Install dependencies
                command: |
                  choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
                  choco install -y mkdocs mkdocs-material
                  Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
                  refreshenv
      - when:
          condition:
            not:
              equal: [<< parameters.os >>, linux]
          steps:
            - run:
                name: Install libyaml
                command: |
                  cd contrib/libyaml
                  mkdir build
                  cd build
                  cmake ..
                  cmake --build . --verbose

  build:
    steps:
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build . --verbose
            sudo cmake --install . --verbose

  test:
    steps:
      - run:
          name: Init test
          command: |
            mkdir hello
            cd hello
            doxide init
      - run:
          name: Build test
          command: |
            doxide build
      - run:
          name: MkDocs test
          command: |
            mkdocs build

jobs:

  all:
    parameters: 
      os:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - environment:
          os: << parameters.os >>
      - build
      - test

  deploy:
    executor: linux
    steps:
      - run:
          name: Trigger package update
          command: |
              curl -X POST https://circleci.com/api/v2/project/gh/lawmurray/download.indii.org/pipeline \
                --header "Circle-Token: $CIRCLE_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch": "main"}'

workflows:

  version: 2
  all:
    jobs:
      - all:
          matrix:
            parameters:
              os:
                - linux
                - mac
                - win/default

      - deploy:
          requires:
            - all
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
