version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2204:current
    resource_class: medium

commands:

  environment:
    steps:
      - run:
          name: Install dependencies
          command: |
              sudo apt update --assume-yes
              sudo apt install --assume-yes --no-install-recommends \
                cmake \
                g++ \
                lcov \
                libyaml-dev \
                libcli11-dev
              sudo rm -rf /var/lib/apt/lists/*

  build:
    steps:
      - run:
          name: Build
          command: |
              mkdir build
              cd build
              cmake ..
              cmake --build .
              sudo cmake --install .

  test:
    steps:
      - run:
          name: Init test
          command: |
            mkdir hello
            cd hello
            doxide init
      - run:
          name: Build test
          command: |
            doxide build

jobs:

  all:
    executor: default
    steps:
      - environment
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive --depth 1
      - build
      - test

  deploy:
    executor: default
    steps:
      - run:
          name: Trigger package update
          command: |
              curl -X POST https://circleci.com/api/v2/project/gh/lawmurray/download.indii.org/pipeline \
                --header "Circle-Token: $CIRCLE_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch": "main"}'

workflows:

  version: 2
  all:
    jobs:
      - all

      - hold:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - deploy:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
